### ISSUE TITLE
Distinguish source code from examples

### ISSUE THREAD

**Issue by 0xCoto** [DataStories-UniPi/miniDB#1]
It appears that the true package dependencies are [`database.py`](https://github.com/DataStories-UniPi/miniDB/blob/master/database.py), [`table.py`](https://github.com/DataStories-UniPi/miniDB/blob/master/table.py) and [`btree.py`](https://github.com/DataStories-UniPi/miniDB/blob/master/btree.py), whereas the rest of the files are sample applications of miniDB. I would suggest moving the example scripts to a new directory (e.g. `/examples`) in order to distinguish them from the source code of miniDB.

**Comment by giorgostheo** [comment]
This is part of the the larger #18 issue.
