### ISSUE TITLE
Make miniDB dependency free

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#10]
Removing the last 2 deps (numpy will be removed asap) would be VERY nice. 

This means:
* Replacing tabulate with a hand made table print function
* Detecting whether graphviz is installed and either save the dot file (if no gv) or plot (if gv is installed). Gv whould still be recommended since it is very useful for ploting btrees, but miniDB would be fully functional without it.

**Comment by giorgostheo** [comment]
Removing tabulate is very important imo. By removing it miniDB becomes dep-free (other deps are optional and are not used in the base pyfiles (database.py, table.py).

**Comment by BL-EVER** [comment]
Make also a barebones version for use in Docker
