### ISSUE TITLE
Keywords appearing in dict values of mdb.py

### ISSUE THREAD

**Issue by mataktelis11** [DataStories-UniPi/miniDB#147]
When the parsing is done in **mdb.py**, the keywords **"group by"** and **"order by"** appear in multiple times in the created dictionary.
Here is an example with **"order by"**:
![Screenshot from 2022-05-19 18-02-50](https://user-images.githubusercontent.com/61196956/169329287-5e182b54-1868-4edd-8e5c-455fe0ee819b.png)

Notice that in the dict value **"from"** the keyword **"order"** appears.
Similarly, with **"group by"**:
![Screenshot from 2022-05-19 18-03-09](https://user-images.githubusercontent.com/61196956/169330583-51494c56-30f8-4c4b-a464-c805d6638555.png)

This results in additional checks by the **mdb.py**, since the keywords need to removed separately e.g. by using removesuffix multiple times.

**Comment by mataktelis11** [comment]
There seems to be a bug with the change you made. When i run **create table** the script freezes. Can you verify if **create table** works?

**Comment by giorgostheo** [comment]
yeah youre right... I have no idea why. I will look into it after lunch
