### ISSUE TITLE
Dictionary structure for aggregate functions

### ISSUE THREAD

**Issue by mataktelis11** [DataStories-UniPi/miniDB#148]
The dictionary structure regarding the aggregate functions in **select** and **having** needs to change as it causes more query parsing to be done outside of **mdb.py**.
Let the following query:
```sql
select max(salary), min(salary) from workers group by department having max(salary) < 4000
```
the **mdb.py** file creates this dictionary:
```
{'select': 'max ( salary ) , min ( salary )',
 'distinct': False,
 'from': 'workers',
 'where': None,
 'group by': 'department',
 'having': 'max ( salary ) < 4000',
 'order by': None,
 'top': None}
```
This forces additional parsing to be done in the **table.py** file which is not ideal.
A possible solution for the select list only could be the following:

```
 {'select_cols': 'salary,salary',
 'select_aggs': 'max, min'
 'distinct': False,
 'from': 'workers',
 'where': None,
 'group by': 'department',
 'having': 'max ( salary ) < 4000',
 'order by': None,
 'top': None}
```
it is not obvious however if the same idea would work for **having**.

**Comment by giorgostheo** [comment]
The more I look at this the more I do not like solution 2. Select and having should remain as is, but the additional sql parsing should take place in database.py instead of table.py. Is that easy to implement?

**Comment by mataktelis11** [comment]
I'm not sure if the additional sql parsing taking place in database.py would change anything. It would still pass data of some form to table.py right?

Maybe a completely new way of parsing is required. There are some libraries in python that can do parsing (i came across this https://pypi.org/project/sqlparse/) but this may not be what you are looking for.
