### ISSUE TITLE
Add support for values in quotes

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#153]
Currently, if a value that appears in the right side of a condition is inside quotes, the miniDB interpreter will not consider the containing strings as one. 

Given that the first command shown works, I am not sure if the fix is as simple as removing the quotes. However, the correct implementation should taking into account that if there are strings in quotes, then these strings should be one "word".

![image](https://user-images.githubusercontent.com/15364873/175900520-4d16d075-18f3-4a2c-84c1-1a73f2de2cc7.png)

Another question is whether the first command should error or not... I think it looks kind of bad. I am not so sure though.

**Comment by Stratis-Dermanoutsos** [comment]
It has been solved in #152.
I believe this issue can close now.
