### ISSUE TITLE
Changing the project structure

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#18]
Rn the the main src files (database, table) are in the same dir as others (btree and misc files). This should change to make the project more readable and lead - eventually - to PyPi.

I will read into this and maybe update the issue down the road.

**Comment by 0xCoto** [comment]
How does this issue differ from #1?

**Comment by giorgostheo** [comment]
This is meant to be a more general issue that aims to solve:

- Current file structure 
- Planning for the future structure (will include tests, examples etc)
- Splitting up current files (esp database) to smaller, more managable and easier to understand ones. 

Will close #1 and point to here...

**Comment by giorgostheo** [comment]
This will be closed for now and will be reopened when the project will be pushed to PyPi
