### ISSUE TITLE
Push project to PyPi

### ISSUE THREAD

**Issue by 0xCoto** [DataStories-UniPi/miniDB#3]
The "intended" way of installing miniDB is currently through git (cloning and running an example `.py` file).

This poses a couple of problems, which are directly addressed if the project is pushed to [PyPi](https://pypi.org/):
- In order to update to a newer version of miniDB, you'd have to re-clone the repository. With `pip`, you can simply run `pip install -U mini-db`*)
- Installation is inconvenient (imagine having to git clone every Py package to a local directory (e.g. `~/Desktop`) - it'd be a bit of a mess!). With `pip`, it's as simple as `pip install mini-db` and you don't have to worry about "where should I install the package"
- Usage is also a bit inconvenient, because working with relative paths implies you have to be careful with how you handle directories, as custom scripts and DB files are placed in the same directory as the source code of miniDB (see relevant issue (#1)). It also matters which path you run your Python scripts from!**

\* [`minidb` is taken](https://pypi.org/project/minidb/), but [`mini-db` is an available package name](https://pypi.org/project/mini-db/) on PyPi! 😁

\*\* This is because
```python
from database import Database
```
tries to find `database.py` in your current path, so you essentially need to have all your scripts in the same directory, or `import database` will fail.

**Comment by giorgostheo** [comment]
This will be closed for now and will be reopened when new features will be added. Q1 2021 proly.
