### ISSUE TITLE
Change savedir structure and adding setup

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#4]
Current savedir structure is:

current_dir/dbdata/
├── db1/
│      ├── table1.pkl
│      ├── table2.pkl
│      ├── ...
├── db2/
│      ├── table1.pkl
│      ├── table2.pkl
│      ├── ...

Changing this to a more standardized structure (moving it to /home/ for ex. and making it hidden), as well as including a setup script that creates the tree would be nice.

**Comment by 0xCoto** [comment]
> as well as including a setup script that creates the tree would be nice.

Does this imply adding a functionality for simply *printing* the structure? Also, perhaps a variation of the [`plot(self)` function](https://github.com/DataStories-UniPi/miniDB/blob/master/btree.py#L228-L258) in `btree.py` could also be utilized in a similar fashion to plot a visually-appealing graph of the tree to the user (useful if there tree gets big and hard to read!).

**Comment by giorgostheo** [comment]
Just creating the folder structure at the home directory is what I had in mind. The setup script would include setup commands like creating that folder structure (or any future folder structure if this one proves to be inefficient) as well as possible server setup (if server-client is a ever a thing in miniDB) e.t.c. Probably useful for PyPI stuff too. 

Plotting the directory tree structure is an interesting idea that needs its own issue IMO.

**Comment by BL-EVER** [comment]
Make the root directory of the tree configurable on setup (maybe through a properties.json file?) so when it is run in a container it can be mapped to a volume.
