### ISSUE TITLE
Documentation - Read the Docs

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#61]
Document the current codebase both in code and externally. Since Read the Docs is the standard for open source (especially python), use that. This needs to be ongoing since any and all new code needs to be documented. Self hosting is not a top priority, but it can happen.

**Comment by 0xCoto** [comment]
Function docstrings need to be revised and rewritten in a slightly different format, including a brief description and the expected type for each argument. This is not only necessary to build a complete references page for RTD, but to also enable direct accessibility to the in-line documentation via `help(database.*)`.

**Comment by 0xCoto** [comment]
Current docstring format is not very descriptive:
```python
def load(self, path):
	'''
	Load all the tables that are part of the db (indexs are noted loaded here)
	'''
```
All function docstrings should contain:
- A **brief** description of what the role of the function is
- _Input_
- - Function arguments
- - - Datatypes
- - - Units (if applicable)
- _Output_
- - Datatype
- - Unit (if applicable)

This information shall be encapsulated in docstrings in the following format:

```python
def compute_foo(x, y, z):
	'''
	Compute something related to the database.
	
	Args:
		x: bool. Some parameter
		y: float. Some other parameter [kB]
		z: string. A piece of text
	
	Output: Result of bar (float)
	'''
```

This can then be transformed to the format that Read the Docs likes (`.rst`):

```rst
.. function:: compute_foo(x, y, z)

   Compute something related to the database.

   :param x: Some parameter
   :type x: bool
   :param y: Some other parameter [kB]
   :type y: float
   :param z: A piece of text
   :type z: string

   Output: Result of bar (*float*)
```

**Comment by 0xCoto** [comment]
Code in need of documentation:
- `database.py`
- `table.py`
- `misc.py`
- `preview.py`
- `btree.py`

**Comment by 0xCoto** [comment]
In-line documentation finished for all files (`database.py`, `table.py`, `preview.py` and `btree.py`): https://github.com/0xCoto/miniDB/commit/082cf266615bae0e086b5826ae41b34a261a19e9

Will commit once ReadTheDocs pages (`/docs`) are ready (this should take a bit more effort).
