### ISSUE TITLE
SQL Compiler 

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#62]
Add a usable SQL compiler that follows the compiler literature as much as possible. The SQL compiler needs to be easy to grasp and extend, since any newly added functionality will need to be accompanied by a new query.

**Comment by 0xCoto** [comment]
@BL-EVER – Have you tested [`insert/sqlInterpreter.py`](https://github.com/DataStories-UniPi/miniDB/blob/feature-sql-compiler/src/insert/sqlInterpreter.py) on its own (or do you call it from somewhere else)?

I get an import error:
```
Traceback (most recent call last):
  File "sqlInterpreter.py", line 1, in <module>
    from ..db import database as Database
ValueError: attempted relative import beyond top-level package
```
Looks like it doesn't work very well with importing `../db/database.py`:
```python
from ..db import database as Database
```

I got it to work (tested it locally) with the following path fix, so I'd consider committing the fix to the [`feature-sql-compiler` branch](https://github.com/DataStories-UniPi/miniDB/tree/feature-sql-compiler):
```python
import os, sys
currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)

from db import database as Database
```
