### ISSUE TITLE
Journals - Logs 

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#67]
Implement journals that keep track of the previously executed commands and can rollback to a previous state. Also add support for more verbose logging.

**Comment by 0xCoto** [comment]
Logs and journals are pretty much done. Journals implemented in the [`feature-server-client`](https://github.com/DataStories-UniPi/miniDB/tree/feature-server-client) branch (so don't expect a separate branch to be made for this feature).
