### ISSUE TITLE
Server-Client protocol 

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#68]
Design and implement a minimal server-client communication protocol. Since such an implementation can be very taxing with regards to performance, whether this will be added and to what extent will be discussed when the performance penalty added is evaluated.

**Comment by 0xCoto** [comment]
(Note so I don't forget: There seems to be a little bug that, upon the submission of an empty query (just pressing enter), the client freezes and doesn't respond. This can be fixed very easily though, e.g. using client-side condition (`if msg == ''` ...)).
