### ISSUE TITLE
Dashboard - SQL command parser 

### ISSUE THREAD

**Issue by giorgostheo** [DataStories-UniPi/miniDB#69]
Design a simple and minimal dashboard that shows meta-tables and/or stats for each database and support the execution of SQL queries (REPL like).

**Comment by 0xCoto** [comment]
@BL-EVER – Have you tested [`insert/sqlInterpreter.py`](https://github.com/DataStories-UniPi/miniDB/blob/feature-sql-compiler/src/insert/sqlInterpreter.py) on its own (or do you call it from somewhere else)?

I get an import error:
```
Traceback (most recent call last):
  File "sqlInterpreter.py", line 1, in <module>
    from ..db import database as Database
ValueError: attempted relative import beyond top-level package
```
Looks like it doesn't work very well with importing `../db/database.py`:
```python
from ..db import database as Database
```

I got it to work (tested it locally) with the following path fix, so I'd consider committing the fix to the [`feature-sql-compiler` branch](https://github.com/DataStories-UniPi/miniDB/tree/feature-sql-compiler):
```python
import os, sys
currentdir = os.path.dirname(os.path.realpath(__file__))
parentdir = os.path.dirname(currentdir)
sys.path.append(parentdir)

from db import database as Database
```
